#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

if [[ -z "$2" ]]; then
  echo "Missing app name" >&2
  exit 1
fi

app=$2
path=`sed 's/&/\&/g' <<<"/${3#/}"`

"$PLUSHU_ROOT/lib/runhook" app-domains "$app" | sed "s ^.*\$ http://&$path"
