#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -z "$2" ]]; then
  echo "Missing app name" >&2
  exit 1
fi

app=$2
domains="${@:3}"
app_dir=$PLUSHU_ROOT/apps/$app
domain_file=$app_dir/domains

fsed () {
  sed -e 's/[]\/$*.^|[]/\\&/g' <<<"$1"
}

for domain in "${domains[@]}"; do
  sed -i "/^$(fsed "$domain")\$/ d" "$domain_file"
done

"$PLUSHU_ROOT/lib/plushook" deploy-app "$app"
