#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_ROOT/apps/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

domains="${@:2}"
domain_file=$app_dir/domains

fsed () {
  sed -e 's/[]\/$*.^|[]/\\&/g' <<<"$1"
}

for domain in "${domains[@]}"; do
  sed -i "/^$(fsed "$domain")\$/ d" "$domain_file"
done

"$PLUSHU_ROOT/lib/plushook" deploy-app "$app"
